# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TeachertList.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1041, 664)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 351, 61))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.txt_teacherid = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_teacherid.setObjectName("txt_teacherid")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.txt_teacherid)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.txt_branch = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.txt_branch.setObjectName("txt_branch")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.txt_branch)
        self.btn_new = QtWidgets.QPushButton(self.centralwidget)
        self.btn_new.setGeometry(QtCore.QRect(90, 70, 81, 28))
        self.btn_new.setObjectName("btn_new")
        self.btn_view = QtWidgets.QPushButton(self.centralwidget)
        self.btn_view.setGeometry(QtCore.QRect(0, 70, 81, 28))
        self.btn_view.setObjectName("btn_view")
        self.btn_delete = QtWidgets.QPushButton(self.centralwidget)
        self.btn_delete.setGeometry(QtCore.QRect(270, 70, 81, 28))
        self.btn_delete.setObjectName("btn_delete")
        self.tbl_teachers = QtWidgets.QTableWidget(self.centralwidget)
        self.tbl_teachers.setGeometry(QtCore.QRect(0, 120, 771, 201))
        self.tbl_teachers.setObjectName("tbl_teachers")
        self.tbl_teachers.setColumnCount(0)
        self.tbl_teachers.setRowCount(0)
        self.btn_save = QtWidgets.QPushButton(self.centralwidget)
        self.btn_save.setGeometry(QtCore.QRect(180, 70, 81, 28))
        self.btn_save.setObjectName("btn_save")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1041, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Teacher ID"))
        self.label_2.setText(_translate("MainWindow", "Branch"))
        self.btn_new.setText(_translate("MainWindow", "New"))
        self.btn_view.setText(_translate("MainWindow", "View"))
        self.btn_delete.setText(_translate("MainWindow", "Delete"))
        self.btn_save.setText(_translate("MainWindow", "Save"))
